"""add_logo_url_to_clubs_and_image_url_to_events

Revision ID: 48e9def8ccd3
Revises: 8c2b7e9a4d51
Create Date: 2026-07-28 20:02:41.348003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e9def8ccd3'
down_revision = '8c2b7e9a4d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(), nullable=True))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
