"""add status column to clubs, default approved for existing rows

Revision ID: 5df4f47ee4dd
Revises: 2468f5ea582a
Create Date: 2026-07-24 02:39:49.168302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df4f47ee4dd'
down_revision = '2468f5ea582a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), server_default='approved', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
